
# Master Thesis: Operating System Support for Reconfigurable Cache
# Student name: Vignesh Makeswaran
# Department of Computer Science
# University of Paderborn
# 2015


# Makefile to compile Reconfigurable Cache user application 

# For FPGA SPARC compiler is used
CC=sparc-linux-gcc

# For LOCAL system GCC compiler is used 
#CC=gcc

all: 
	$(CC) -o reconf_cache reconfig_cache_app.c

# Removes the executable user application and temporary files in the current folder
clean: 
	rm reconf_cache *~


